import 'interfaces.dart';
import 'utils.dart';

var deck1 = <String, String>{
  getCardId(Rank.ace, Suit.diamonds): "set1/ace_of_diamonds.svg",
  getCardId(Rank.ace, Suit.hearts): "set1/ace_of_hearts.svg",
  getCardId(Rank.ace, Suit.clubs): "set1/ace_of_clubs.svg",
  getCardId(Rank.ace, Suit.spades): "set1/ace_of_spades.svg",
  getCardId(Rank.two, Suit.diamonds): "set1/2_of_diamonds.svg",
  getCardId(Rank.two, Suit.hearts): "set1/2_of_hearts.svg",
  getCardId(Rank.two, Suit.clubs): "set1/2_of_clubs.svg",
  getCardId(Rank.two, Suit.spades): "set1/2_of_spades.svg",
  getCardId(Rank.three, Suit.diamonds): "set1/3_of_diamonds.svg",
  getCardId(Rank.three, Suit.hearts): "set1/3_of_hearts.svg",
  getCardId(Rank.three, Suit.clubs): "set1/3_of_clubs.svg",
  getCardId(Rank.three, Suit.spades): "set1/3_of_spades.svg",
  getCardId(Rank.four, Suit.diamonds): "set1/4_of_diamonds.svg",
  getCardId(Rank.four, Suit.hearts): "set1/4_of_hearts.svg",
  getCardId(Rank.four, Suit.clubs): "set1/4_of_clubs.svg",
  getCardId(Rank.four, Suit.spades): "set1/4_of_spades.svg",
  getCardId(Rank.five, Suit.diamonds): "set1/5_of_diamonds.svg",
  getCardId(Rank.five, Suit.hearts): "set1/5_of_hearts.svg",
  getCardId(Rank.five, Suit.clubs): "set1/5_of_clubs.svg",
  getCardId(Rank.five, Suit.spades): "set1/5_of_spades.svg",
  getCardId(Rank.six, Suit.diamonds): "set1/6_of_diamonds.svg",
  getCardId(Rank.six, Suit.hearts): "set1/6_of_hearts.svg",
  getCardId(Rank.six, Suit.clubs): "set1/6_of_clubs.svg",
  getCardId(Rank.six, Suit.spades): "set1/6_of_spades.svg",
  getCardId(Rank.seven, Suit.diamonds): "set1/7_of_diamonds.svg",
  getCardId(Rank.seven, Suit.hearts): "set1/7_of_hearts.svg",
  getCardId(Rank.seven, Suit.clubs): "set1/7_of_clubs.svg",
  getCardId(Rank.seven, Suit.spades): "set1/7_of_spades.svg",
  getCardId(Rank.eight, Suit.diamonds): "set1/8_of_diamonds.svg",
  getCardId(Rank.eight, Suit.hearts): "set1/8_of_hearts.svg",
  getCardId(Rank.eight, Suit.clubs): "set1/8_of_clubs.svg",
  getCardId(Rank.eight, Suit.spades): "set1/8_of_spades.svg",
  getCardId(Rank.nine, Suit.diamonds): "set1/9_of_diamonds.svg",
  getCardId(Rank.nine, Suit.hearts): "set1/9_of_hearts.svg",
  getCardId(Rank.nine, Suit.clubs): "set1/9_of_clubs.svg",
  getCardId(Rank.nine, Suit.spades): "set1/9_of_spades.svg",
  getCardId(Rank.ten, Suit.diamonds): "set1/10_of_diamonds.svg",
  getCardId(Rank.ten, Suit.hearts): "set1/10_of_hearts.svg",
  getCardId(Rank.ten, Suit.clubs): "set1/10_of_clubs.svg",
  getCardId(Rank.ten, Suit.spades): "set1/10_of_spades.svg",
  getCardId(Rank.jack, Suit.diamonds): "set1/jack_of_diamonds.svg",
  getCardId(Rank.jack, Suit.hearts): "set1/jack_of_hearts.svg",
  getCardId(Rank.jack, Suit.clubs): "set1/jack_of_clubs.svg",
  getCardId(Rank.jack, Suit.spades): "set1/jack_of_spades.svg",
  getCardId(Rank.queen, Suit.diamonds): "set1/queen_of_diamonds.svg",
  getCardId(Rank.queen, Suit.hearts): "set1/queen_of_hearts.svg",
  getCardId(Rank.queen, Suit.clubs): "set1/queen_of_clubs.svg",
  getCardId(Rank.queen, Suit.spades): "set1/queen_of_spades.svg",
  getCardId(Rank.king, Suit.diamonds): "set1/king_of_diamonds.svg",
  getCardId(Rank.king, Suit.hearts): "set1/king_of_hearts.svg",
  getCardId(Rank.king, Suit.clubs): "set1/king_of_clubs.svg",
  getCardId(Rank.king, Suit.spades): "set1/king_of_spades.svg",
};





